#include <iostream>
#include <exception>
using namespace std;

int main() {
    int x[] = {10, 20, 30, 40};
    int index;
    cout << "Enter index: ";
    cin >> index;

    try {
        if (index < 0 || index >= sizeof(x)/sizeof(x[0])) 
            throw out_of_range("The element is an array index out of boundary.");
        cout << "Element at index " << index << " is " << x[index] << '\n';
    } catch (const out_of_range& e) {
        cout << e.what() << '\n';
    } catch (const exception& e) {
        cout << "Invalid input.\n";
    }
    return 0;
}
out put:
Enter index: 2
Element at index 2 is 30
